### PR TITLE
added pull request Template

### LINKED ISSUE #87: Create a Pull Request template
To create the template please take reference from [here](https://github.com/json-schema-org/website/blob/main/.github/pull_request_template.md)

### PR DESCRIPTION
**Pull request by Vishv0407**
Closes #87 
Added a template code markdown file as pull_request_template.md

### CODE REVIEW

**Comment by JeelRajodiya** [comment]
@Vishv0407 
please move the PR template file under the `./github` folder (as we have in the website repo)

image

**Review by JeelRajodiya — CHANGES_REQUESTED** [review]
please see my comment

**Comment by Vishv0407** [comment]
@JeelRajodiya I have changed file location. Please once review.

**Comment by JeelRajodiya** [comment]
Great work!

**Pull request merged**
