### PR TITLE
Hydration Error Turbopack Issue

### PR DESCRIPTION
**Pull request by RonakSurana-2001**
Earlier the providers.js was not according to next.js 13. See Guide
[https://v2.chakra-ui.com/getting-started/nextjs-app-guide](url)

Changed Providers and issue was resolved. #10

### CODE REVIEW

**Review by JeelRajodiya — CHANGES_REQUESTED** [review]
We still have this hydration error 
image
image

**Comment by RonakSurana-2001** [comment]
@JeelRajodiya Can you please share command which you are running.
In my side my am running pnpm dev and it is showing no error.

**Comment by JeelRajodiya** [comment]
sure! I am sharing my logs.
I am running `pnpm run dev` (it gives me the same result with `pnpm dev`) 
image
image

**Comment by RonakSurana-2001** [comment]
Okk I understood

**Comment by JeelRajodiya** [comment]
@RonakSurana-2001 Are you opening the project in localhost? The errors only appear when you visit dev preview. 
 
image

**Comment by RonakSurana-2001** [comment]
Yes I saw give me few Minutes.

**Pull request closed without merging**
