### PR TITLE
feat: prettify code in code editor

### LINKED ISSUE #77: Feature: Prettify code in the code editor
Currently, we have alt+shift+f shortcut to format the code in the code editor of the tour. 

Setup formatting the code in a timely manner (when the code in the editor is complete, meaning it is not an invalid json)

(e.g. It should format the code in the text editor every 1 second.)

### PR DESCRIPTION
**Pull request by pavanydg**
**What kind of change does this PR introduce?**
Prettify the code in code editor every 1 second.

**Issue Number:**

-  Closes #77  
-  Related to #52  
-  Others? 

**Screenshots/videos:**

[Screencast from 12-08-2024 01:22:05 AM.webm](https://github.com/user-attachments/assets/d297feda-57e6-4943-9fbc-62880176d0a7)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

### CODE REVIEW

**Comment by pavanydg** [comment]
@JeelRajodiya pl review.

**Comment by pavanydg** [comment]
@JeelRajodiya any changes required?

**Comment by JeelRajodiya** [comment]
I am reviewing your PR right now.

**Review by JeelRajodiya — APPROVED** [review]

**Comment by JeelRajodiya** [comment]
@pavanydg Well done, The feature is implemented correctly! 

I had to remove the timely formatting because it was adding too may useEffects (total 6 useEffects) in the component. Intead, now it formats the code when it is being validated.

**Comment by pavanydg** [comment]
@JeelRajodiya Yeah sure.

**Pull request merged**
